# Generated by Django 2.2.1 on 2019-05-15 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='in_main_menu',
            field=models.BooleanField(default=False, help_text='If this is checked, the page will be visible in main menu.', verbose_name='show in main menu'),
        ),
    ]
