# Generated by Django 2.2.1 on 2019-05-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='in_main_menu',
            field=models.BooleanField(default=False, verbose_name='view in main menu'),
        ),
    ]
