# Generated by Django 2.2.1 on 2019-06-01 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opages', '0002_page_in_main_menu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'page', 'verbose_name_plural': 'pages'},
        ),
        migrations.AlterModelTable(
            name='page',
            table='dapricot_pages_page',
        ),
    ]
