# Generated by Django 2.2.1 on 2019-05-01 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('creation_date',), 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
    ]
