# Generated by Django 2.2.1 on 2019-05-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oblog', '0002_auto_20190501_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
